#!/bin/bash

# TODO: desc

source vpFunctions.sh

# Get screenshot directory
ssDir=$(getScreenshotDir)

# Iterate over screenshots in folder
for ssFile in $(ls "$ssDir")
do
	# Extract vp name from each screenshot
	vpName=$(getVPName $ssFile)
	vpDir=$(getVPDir)

	for vpFile in $(find "$vpDir" -name "${vpName}*")
	do
		# Print name of current comparison
		echo ${vpFile#${vpDir}}

		# TODO make robust to names that start the same

		# Compare via utility
		/opt/squish-6.4/bin/vpdiff "$vpFile" "junk" "$ssDir$ssFile"
	done
done
